### PR TITLE
Allow to upgrade to Scala.js 1.15.0

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
Still a draft, because we need to figure out how to exclude the new `scalajs-scalalib_2.13` artifacts (they contain the Scala.js version in the build metadata, e.g. `2.13.12+1.15.0`).

/cc @sjrd

**Comment by gzm0** [comment]
I found what I needed :) Please review by @sjrd in addition to a reviewer for scala-steward. (Sorry, I can't assign a reviewer).

**Review by mzuehlke — APPROVED** [review]
From steward side this looks good 👍

**Review by sjrd — APPROVED** [review]
The new scheme for `scalajs-scalalib` looks good to me.

**Pull request merged**
