### PR TITLE
Support Basic Auth for GitHub again

### PR DESCRIPTION
**Pull request by joan38**
Fix for #3480
cc @nikita-ty754 @mzuehlke

### CODE REVIEW

**Comment by joan38** [comment]
Not sure what's the issue with the build

**Comment by mzuehlke** [comment]
https://github.com/scalameta/scalafmt/issues/4571 is the issue

**Comment by joan38** [comment]
Sounds like we are blocked?

**Comment by joan38** [comment]
Sounds like we are blocked?

**Comment by joan38** [comment]
@mzuehlke all good now

**Review by mzuehlke — APPROVED** [review]
Thanks for reacting that fast 👍

**Pull request merged**
