### PR TITLE
Add support for PR labels

### LINKED ISSUE #1471: Add labels to GitHub PRs (not just in description)
https://github.com/fthomas/scala-steward/issues/404 (and #755) added labels to the description of PRs. 

It would be nice to be able to add proper labels (when you have access to do so, or opt-in) to the pull requests.

### PR DESCRIPTION
**Pull request by ybasket**
Takes a stab at #1471 to make the PR/MR labels appear not only in the textual description, but also using the git hoster's native labelling feature. Implemented for GitHub and GitLab, Bitbucket doesn't have a native label feature, only a plugin (for which support could be added later, now the implementation just logs a warning). It's opt-in for now as it's a change in behaviour not every user might appreciate, but could be promoted to a default later on.

Note: GitHub creates the labels with a standard grey colour (first screenshot), but the user can update that (see second).

PS: Scala Steward is not only a great help, but also a very nice codebase to work with, thank you!

Closes #1471 

Screenshot 2022-02-12 at 11 50 44
Screenshot 2022-02-12 at 12 04 08
Screenshot 2022-02-12 at 12 25 18

### CODE REVIEW

**Review by exoego — APPROVED** [review]
LGTM

**Comment by ybasket** [comment]
> Long awaited feature! Thanks for implementing it! 
> 
> 
> 
> It would be great to be able to configure (in the repo config) a subset of labels that Scala Steward will create. Some of the labels in the description are currently redundant and not all of them might be relevant to the project's workflow, so creating all of them might be a bit too noisy.

Glad to hear it's of use to someone 🙂 

I thought about the filtering too and imagined this PR's feature could be augmented by some regex or another, maybe more semantic mechanism to filter the labels (not only on the PR, also in the body). But I concluded it deserves a separate PR. Chances are there that I find the time to do it once this one is merged.

**Comment by ybasket** [comment]
@fthomas Codacy is unhappy about something that only got reformatted and test coverage is on a level where I don't see ways to reasonably improve it further. From my side the PR is hence ready to merge, unless you see something to take care of still?

**Comment by TonioGela** [comment]
Any updates?

**Comment by exoego** [comment]
@fthomas Do you have a time to test this with your test Steward instance ??

**Comment by andresld** [comment]
Hi! Is there any update about this?

**Comment by exoego** [comment]
Thanks and sorry for keeping you waiting 🙇 
I will make a new release soon.

**Comment by leobenkel** [comment]
is this usable through the .scala-steward.conf file ? or in the github action ?

**Comment by ybasket** [comment]
> is this usable through the .scala-steward.conf file ? or in the github action ?

Depending on how you run Scala Steward, either just add `--add-labels` to the command line actions or supply

```yaml
with:
  other-args: '--add-labels'
```

to the GitHub action.

**Comment by leobenkel** [comment]
> I was not able to make it work with the github action. I think that it is expected to place the argument in the `other-args` input, but it looks like this one is not correctly recognized:
> 
> ```
> Unexpected input(s) 'other-args', valid inputs are ['repos-file', 'github-repository', 'github-token', 'author-email', 'author-name', 'scala-steward-version', 'coursier-cli-url', 'ignore-opts-files', 'branches', 'sign-commits', 'signing-key', 'timeout', 'cache-ttl', 'github-api-url', 'scalafix-migrations', 'artifact-migrations', 'github-app-id', 'github-app-key', 'repo-config']
> ```

yes ok , i have the same experience with other-args not being valid :/

**Comment by leobenkel** [comment]
@andresld I added https://github.com/scala-steward-org/scala-steward-action/issues/386

**Comment by leobenkel** [comment]
@andresld it would be nice if it was in the `.scala-steward.conf` since there is already a `commit.message` , there could be a `commit.labels`

**Comment by leobenkel** [comment]
@ybasket and @andresld , it has been fixed , see: https://github.com/scala-steward-org/scala-steward-action/issues/386#issuecomment-1209116897

**Pull request merged**
