### PR TITLE
Restrict Scala CLI detection to `.sc` and `.scala` files

### LINKED ISSUE #2948: `java.io.IOException: Cannot run program "scala-cli"`
I'm a little puzzled what's going on 🤔 

https://github.com/typelevel/steward/actions/runs/4034855994/jobs/6936380468

```
2023-01-29 03:14:57,119 ERROR Steward typelevel/cats-effect:series/3.x failed
  java.io.IOException: Cannot run program "scala-cli" (in directory "/home/runner/scala-steward/workspace/repos/typelevel/cats-effect"): error=2, No such file or directory
  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
  	at org.scalasteward.core.io.process$.$anonfun$createProcess$5(process.scala:81)
  	at flatMap @ org.scalasteward.core.io.process$.createProcess(process.scala:79)
  	at flatMap @ org.scalasteward.core.io.process$.slurp(process.scala:43)
  	at delay @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.isDebugEnabled(Slf4jLoggerInternal.scala:65)
  	at ifM$extension @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.info(Slf4jLoggerInternal.scala:91)
  	at >>$extension @ org.scalasteward.core.io.ProcessAlg$.$anonfun$create$1(ProcessAlg.scala:92)
  	at map @ org.scalasteward.core.buildtool.scalacli.ScalaCliAlg.$anonfun$getDependencies$2(ScalaCliAlg.scala:54)
  	at flatMap @ org.scalasteward.core.buildtool.scalacli.ScalaCliAlg.$anonfun$getDependencies$2(ScalaCliAlg.scala:54)
  	at map @ org.scalasteward.core.buildtool.scalacli.ScalaCliAlg.getDependencies(ScalaCliAlg.scala:50)
  	at flatMap @ org.scalasteward.core.buildtool.scalacli.ScalaCliAlg.getDependencies(ScalaCliAlg.scala:50)
  	at delay @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.$anonfun$info$4(Slf4jLoggerInternal.scala:91)
  	at delay @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.isInfoEnabled(Slf4jLoggerInternal.scala:66)
  	at ifM$extension @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.info(Slf4jLoggerInternal.scala:91)
  	at >>$extension @ org.scalasteward.core.io.ProcessAlg$.$anonfun$create$1(ProcessAlg.scala:92)
  Caused by: java.io.IOException: error=2, No such file or directory
  	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
  	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
  	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
  	at org.scalasteward.core.io.process$.$anonfun$createProcess$5(process.scala:81)
  	at cats.effect.unsafe.WorkerThread.blockOn(WorkerThread.scala:631)
  	at scala.concurrent.package$.blocking(package.scala:124)
  	at cats.effect.IOFiber.runLoop(IOFiber.scala:953)
  	at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1325)
  	at cats.effect.IOFiber.run(IOFiber.scala:119)
  	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:585)
  2023-01-29 03:14:57,126 INFO  ──────────── Total time: Steward typelevel/cats-effect:series/3.x: 1m 32s 74ms 
```

### PR DESCRIPTION
**Pull request by fthomas**
Closes #2948

### CODE REVIEW

**Review by alejandrohdezma — APPROVED** [review]
Should we have a test checking any other extension is not treated as a Scala CLI build?

**Comment by mzuehlke** [comment]
Shouldn't we check if the `scala-cli` executable is available and then either complain and stop processing  totally, or disable the `ScalaCliAlg` ?

**Comment by fthomas** [comment]
> Shouldn't we check if the `scala-cli` executable is available and then either complain and stop processing totally, or disable the `ScalaCliAlg` ?

Yeah, we could do that. But if we do, this should be the same for all build tools (`mvn`, `mill`, `sbt`, and `scala-cli`). Currently we just expect that they are available and fail hard if a build uses them but they are not available. I would propose to discuss this in a separate issue, if we want to discuss it. :-)

**Comment by mzuehlke** [comment]
I agree, this is a different issue, or not. 
As most people are probably using the Docker image, this is a none issue.

**Comment by fthomas** [comment]
> Should we have a test checking any other extension is not treated as a Scala CLI build?

Good idea, I added a test for that.

**Pull request merged**
