### PR TITLE
add sbt-pgp in artifact-migrations.conf

### PR DESCRIPTION
**Pull request by xuwei-k**
https://github.com/sbt/sbt-pgp/pull/186
https://github.com/sbt/sbt-pgp/releases/tag/v2.1.2-M1
https://repo1.maven.org/maven2/com/github/sbt/sbt-pgp_2.12_1.0/
https://github.com/sbt/sbt/issues/6294

/cc @eed3si9n

### CODE REVIEW

**Comment by mzuehlke** [comment]
Thanks @xuwei-k

**Comment by fthomas** [comment]
Scala Steward ignores this update if the project is not already on a milestone version:
```
INFO  Ignore com.jsuereth:sbt-pgp : 2.1.1 -> 2.1.2-M1 (reason: no suitable next version)
```
Since 2.1.2 is already released, we should bump the version in `artifact-migrations.conf` too.

**Comment by mzuehlke** [comment]
I haven't realised the problem with the milestone version. Sorry

**Comment by fthomas** [comment]
No problem. It just ignored this update until we bumped the version to a non-milestone one.

For the future we could think about using the `VersionsCache` to find all versions of the renamed artifact. Maybe we would not need to specify any version in `artifact-migrations.conf` then.

**Pull request merged**
