### PR TITLE
Let Scala Steward send upgrades to Scala.js 1.8.0.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
Thanks @fthomas :) I like this new process. I hope it's not a burden for you!

**Comment by fthomas** [comment]
You're welcome! And no, it is not a burden for me.

Btw, it took a little while for Scala Steward to create PRs for Scala.js 1.8.0 this time since it was busy with the sbt 1.5.6 update and it is currently slowed down by GitHub's secondary rate limiting (https://github.com/scala-steward-org/scala-steward/issues/2355) which we are not yet mitigating.

**Comment by fthomas** [comment]
Another thing I noticed is this PR https://github.com/com-lihaoyi/mill/pull/1608 which suggests to me that scalajs-sbt-test-adapter is missing in the above list of ignored artifacts.

**Comment by sjrd** [comment]
Oh, well spotted! It was already there, but I had the wrong artifact name. Here is a PR to fix it: #2405.

**Pull request merged**
