### PR TITLE
vcs: add gitea

### PR DESCRIPTION
**Pull request by yaroot**
still WIP

Feature-wise
- [x] do-not-fork
- [x] fork
- [x] label

### CODE REVIEW

**Comment by fthomas** [comment]
@yaroot I would welcome Gitea/Forgejo support in Scala Steward.

Note that it is not required to support forking and labels for this support to be merged. The Bitbucket Server integration for example also [does not support forking and labels](https://github.com/scala-steward-org/scala-steward/blob/c1aa49d38b3d5fa6adf63f59de240680d7f9135b/modules/core/src/main/scala/org/scalasteward/core/vcs/VCSType.scala#L51-L55) (yet).

**Comment by yaroot** [comment]
@fthomas 
Oh I wasn't aware of that, let me see if I can find some time this weekend.

**Comment by yaroot** [comment]
Forking via api doesn't seem to work on my local forgejo setup, I'll debug later.

Labelling is supported, I've hardcoded the color. I'll do another pull request to add an option for that.

**Review by fthomas — APPROVED** [review]
This looks great, many thanks @yaroot!

**Comment by fthomas** [comment]
Just tried this on Codeberg: :tada: https://codeberg.org/fthomas/test-repo-3/pulls/1 :tada: 

This is very cool, @yaroot!

**Pull request merged**
