### PR TITLE
Support artifact migrations in `Update.ForGroupId`

### PR DESCRIPTION
**Pull request by fthomas**
This supports artifact migrations of multiple artifacts in one update. Prior to this change, this was not possible because the `newerGroupId` and `newerArtifactId` fields were discarded while `ForArtifactId` updates were grouped into `ForGroupId`. With this change, `ForGroupId` is just a non-empty list of `ForArtifactId`s, so that these fields are not lost.

Closes: #1974

### CODE REVIEW

**Review by mzuehlke — APPROVED** [review]

**Review by exoego — APPROVED** [review]

**Review by alejandrohdezma — APPROVED** [review]
This is an awesome change, it also simplifies a lot understanding the update hierarchy!

**Comment by fthomas** [comment]
> it also simplifies a lot understanding the update hierarchy!

I agree. Maybe we can simplify it even further in the future by removing `CrossDependency` and adding a new `Update.ForCrossArtifactId`. I could imagine that it looks like this: 
- if we find an update for a `Dependency` (for example `cats-core_2.12`), we wrap it into `ForCrossArtifactId`
- multiple `ForCrossArtifactId`s are grouped into `ForArtifactId` if they have the same groupId, the same newer versions, the same artifactId name, but different artifactId cross names (for example `cats-core_2.12` and `cats-core_2.13`)
- multiple `ForArtifactId` are grouped into `ForGroupId` if they have the same groupId, the same newer versions, but different artifactIds (as it is today)

IMO `CrossDependency` is a bit strange today, since we artificially wrap only one `Dependency` in https://github.com/scala-steward-org/scala-steward/blob/028a0e1cbc0a1c03f7fc9a461e462fb5cfc3148a/modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala#L59 and then later extend the `ForArtifactId.crossDependency` in https://github.com/scala-steward-org/scala-steward/blob/028a0e1cbc0a1c03f7fc9a461e462fb5cfc3148a/modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala#L104

Maybe it becomes simpler if we just use distinct types in these places.

**Comment by mzuehlke** [comment]
> Maybe it becomes simpler if we just use distinct types in these places.

Your proposal sounds really promising 👍

**Comment by fthomas** [comment]
> Maybe it becomes simpler if we just use distinct types in these places.

Ok, I tried this now twice and it always becomes ugly in `PruningAlg` and non-trivial to get rid of `CrossDependency` there. This is probably an indication that `PruningAlg` is itself a mess that would benefit from some clean-up.

**Pull request merged**
