### PR TITLE
Refactored MillAlg to use external plugin project

### PR DESCRIPTION
**Pull request by lefou**
We now generate a version specific predef file, to make
sure we load the correct plugin artifact.

Removed internal mill-plugin module code.

This PR finalizes #2704 .

### CODE REVIEW

**Review by fthomas — APPROVED** [review]
LGTM. Thank you, @lefou!

**Review by exoego — APPROVED** [review]

**Comment by fthomas** [comment]
Just tried this with `scala-steward-org/test-repo-2` and it fails with:
```
nfo] 2022-12-14 07:40:35,333 INFO  ──────────── Steward scala-steward-org/test-repo-2 ────────────
[info] 2022-12-14 07:40:35,333 INFO  Check cache of scala-steward-org/test-repo-2
[info] 2022-12-14 07:40:35,798 INFO  Clone scala-steward/test-repo-2
[info] 2022-12-14 07:40:36,318 INFO  Synchronize with scala-steward-org/test-repo-2
[info] 2022-12-14 07:40:37,236 INFO  Refresh cache of scala-steward-org/test-repo-2
[info] 2022-12-14 07:40:43,184 ERROR Steward scala-steward-org/test-repo-2 failed
[info] java.io.IOException: 'mill -i -p /home/frank/data/code/scala-steward/core/workspace/repos/scala-steward-org/test-repo-2/scala-steward.sc show org.scalasteward.mill.plugin.StewardPlugin/extractDeps' exited with code 1
[info] Compiling /home/frank/data/code/scala-steward/core/workspace/repos/scala-steward-org/test-repo-2/scala-steward.sc
[info] Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom
[info] Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom
[info] Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom.sha1
[info] Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom.sha1
[info] Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom
[info] Downloaded https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom
[info] Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom.sha1
[info] Downloaded https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom.sha1
[info] java.lang.Exception: Failed to resolve ivy dependencies:Error downloading org.scala-steward:scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13:0.17.0
[info]   not found: /home/frank/.ivy2/local/org.scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/ivys/ivy.xml
[info]   not found: https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom
[info]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom
```

**Comment by lefou** [comment]
> Just tried this with `scala-steward-org/test-repo-2` and it fails with:
> 
> ```
> nfo] 2022-12-14 07:40:35,333 INFO  ──────────── Steward scala-steward-org/test-repo-2 ────────────
> [info] 2022-12-14 07:40:35,333 INFO  Check cache of scala-steward-org/test-repo-2
> [info] 2022-12-14 07:40:35,798 INFO  Clone scala-steward/test-repo-2
> [info] 2022-12-14 07:40:36,318 INFO  Synchronize with scala-steward-org/test-repo-2
> [info] 2022-12-14 07:40:37,236 INFO  Refresh cache of scala-steward-org/test-repo-2
> [info] 2022-12-14 07:40:43,184 ERROR Steward scala-steward-org/test-repo-2 failed
> [info] java.io.IOException: 'mill -i -p /home/frank/data/code/scala-steward/core/workspace/repos/scala-steward-org/test-repo-2/scala-steward.sc show org.scalasteward.mill.plugin.StewardPlugin/extractDeps' exited with code 1
> [info] Compiling /home/frank/data/code/scala-steward/core/workspace/repos/scala-steward-org/test-repo-2/scala-steward.sc
> [info] Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom
> [info] Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom
> [info] Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom.sha1
> [info] Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom.sha1
> [info] Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom
> [info] Downloaded https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom
> [info] Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom.sha1
> [info] Downloaded https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom.sha1
> [info] java.lang.Exception: Failed to resolve ivy dependencies:Error downloading org.scala-steward:scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13:0.17.0
> [info]   not found: /home/frank/.ivy2/local/org.scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/ivys/ivy.xml
> [info]   not found: https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom
> [info]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13/0.17.0/scala-steward-mill-plugin_mill$MILL_BIN_PLATFORM_2.13-0.17.0.pom
> ```

Huh, the `$MILL_BIN_PLATFORM` is not expanded. Looks like the `interp.load.ivy` is not using the same registered hock as the `import $ivy`. I'll send fix.

**Comment by lefou** [comment]
Am I assuming right, that the additional snapshot repository was registered in the predef script, because the mill-plugin may have been published as snapshot to it? So, it should be no longer necessary?

**Pull request merged**
