### PR TITLE
Support GitHub Enterprise

### PR DESCRIPTION
**Pull request by joan38**
Same as #3425 but reduced as much as possible

### CODE REVIEW

**Comment by joan38** [comment]
@exoego @alejandrohdezma Ready for review

**Comment by joan38** [comment]
@exoego @alejandrohdezma @mzuehlke ping

**Comment by mzuehlke** [comment]
Thanks @joan38  for the pull request. 
I will try to review it the coming days (life is incredible busy). 
This shouldn't stop anyone else from taking a look .

**Comment by joan38** [comment]
I'm trying one more ping on this 😞

**Review by mzuehlke — APPROVED** [review]
Thanks for the contribution @joan38 
Compared to your first attempt you cut the changes to a third 👍 
I appreciate that you managed keep the CLI unchanged.
I hope that this helps with the adoption of Scala Steward @ Netflix 🚀 

And sorry that I didn't managed to review this earlier 😢

**Comment by joan38** [comment]
Thanks @mzuehlke, this is great!

What is the next step now?

**Pull request merged**
