### PR TITLE
Add `commit-count` label to PR bodies

### LINKED ISSUE #2383: Add new tag for PRs with changes from a Scalafix migration?
A PR with a Scalafix migration does not necessarily contains changes from that migration. Sometimes I'd like to check which of Scala Steward's PRs contains changes from a Scalafix migration but AFAIK there is now easy way to search for these PRs on GitHub. I'm therefore contemplating splitting the current `scalafix-migrations` label into two `scalafix-migrations:changes` and `scalafix-migrations:no-changes` labels to make searching for these easier.

### PR DESCRIPTION
**Pull request by fthomas**
This adds the `commit-count` label to PR bodies. If the PR contains one
commit, the label will be `commit-count:1`. If it contains more than one
commit, the label will be `commit-count:n:$n` where `$n` is the number of
commits.

This allows to search for PRs with multiple but unspecified number of
commits and for PRs with a specified number of commits.

Closes #2383.

### CODE REVIEW

**Comment by mzuehlke** [comment]
What about just the plural ?
* `commit-count:1`
* `commit-counts:$n` for `n > 1`

**Comment by fthomas** [comment]
I would prefer if the string before the `:` does not differ between the two cases. I consider the string before the `:` as the static part of the label and everything after that as dynamic.

**Review by mzuehlke — APPROVED** [review]

**Comment by fthomas** [comment]
It works as expected. We can now search for PRs with one / multiple commits:
* PRs with one commit: https://github.com/pulls?q=author%3Ascala-steward+is%3Apr+%22commit-count%3A1%22
* PRs with multiple commits: https://github.com/pulls?q=author%3Ascala-steward+is%3Apr+%22commit-count%3An%22

**Comment by fthomas** [comment]
Here are the rare cases where Scala Steward created PRs with 3 commits: https://github.com/pulls?q=author%3Ascala-steward+is%3Apr+%22commit-count%3An%3A3%22

**Pull request merged**
