### PR TITLE
Authenticate UrlChecker calls to API host

### LINKED ISSUE #1468: Add release notes/changelog/version diff for dependencies in private GitHub repos
These nice features don't work for dependencies whose git repos are private (thus need auth):
- Release Notes
- Changelog
- Version Diff

This is probably because the http client used for those doesn't seem to use the github token:

https://github.com/fthomas/scala-steward/blob/master/modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala

### PR DESCRIPTION
**Pull request by fthomas**
This authenticates `UrlChecker` calls if the scheme and host of the request URL match `ForgeCfg#apiHost`.

Hopefully fixes #1468.

### CODE REVIEW

**Review by mzuehlke — APPROVED** [review]
interesting that both braches are already covered with the existing tests

**Comment by fthomas** [comment]
> interesting that both braches are already covered with the existing tests

Right. I'll add a test that checks that auth headers are actually added to the request. :-)

**Comment by fthomas** [comment]
Just tested this with a private Bitbucket Server and it works for me. The repo URL, release notes, and version diff are now included in the PR body.

**Review by exoego — APPROVED** [review]
Nice

**Comment by lenguyenthanh** [comment]
This currently doesn't work for private github repositories. because normal url like `https://`github.com/org/private-repository` will not accept any token. So both basic auth and jwt token don't work.

I'm not sure this is a regression or it has never worked?

Can anyone confirm?

**Pull request merged**
