### PR TITLE
Reset update branch before merging the base branch

### LINKED ISSUE #2503: Updated PRs could be broken after merge
https://github.com/typelevel/literally/pull/24 is a PR that was updated because of a merge conflict. The merge conflict was in `.github/workflows/ci.yml` which was changed by Scala Steward via a post-update hook. After the base branch was merged into the update branch, `EditAlg#applyUpdate` ran again but didn't produced any new commits because [the old version could not be found anymore](https://github.com/scala-steward-org/scala-steward/blob/062082487800ecdb172fe710acc1a72c052ba62b/modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala#L58). This broke the CI since `.github/workflows/ci.yml` now contained changes from the first post-update hook and the merge. It could be fixed by running the post-update hook again after the merge.

To fix issues like this, I propose to reset the update branch (i.e. reverting all changes by Scala Steward) before merging in the base branch. By reverting Scala Steward's prior changes and then merging the base branch, the update branch has no diff compared to the head of the base branch. Running `EditAlg#applyUpdate` then again will update the version number and run Scalafix migrations and post-update hooks. The changes Scala Steward would then make are the same as if it would create a completely new PR but on the old update branch.

### PR DESCRIPTION
**Pull request by fthomas**
Closes #2503.

### CODE REVIEW

**Comment by fthomas** [comment]
This change can be seen in action in https://github.com/scala-steward-org/test-repo-2/pull/87.

**Comment by nafg** [comment]
This seems to result in PRs accruing lots of revert commits.

Instead why not recreate the branch from scratch? Why not `git rest` to the base branch and force push?

**Comment by nafg** [comment]
https://github.com/slick/slick/pull/2511 got to **19** commits by the time Mergify merged it!!!

**Comment by nafg** [comment]
This is really bad, any chance of reverting it?

**Comment by fthomas** [comment]
> This is really bad

I find your tone rude. Please be more constructive in future interactions in this project.

**Comment by nafg** [comment]
Apologies, I did not mean it in that way.

Where do we go from here? https://github.com/slick/slick/pull/2491 now has 43 commits.

**Comment by exoego** [comment]
Please open a new issue to collect feedback from community.
PR is also welcome.

**Pull request merged**
